-- MySQL Script generated by MySQL Workbench
-- Wed 29 Mar 2023 10:53:29 AM +00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8mb4 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`groupe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomGroup` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school`.`stagaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`stagaire` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `prenom` VARCHAR(15) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `groupe_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stagaire_groupe_idx` (`groupe_id` ASC) VISIBLE,
  CONSTRAINT `fk_stagaire_groupe`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `school`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
